source 'https://rubygems.org'

gem 'bar', path: '../bar'

group :development, :test do
  gem 'dotenv'
  gem 'pry-byebug'
  gem 'rake'
  gem 'rspec', '~> 3.0'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'webmock'
end
