# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '7.0.4'
gem 'aws-sdk-dynamodb'
gem 'aws-sdk-lambda', '1.91.0'
gem 'aws-sdk-s3', '1.117.2'
gem 'damerau-levenshtein', '1.3.3'
gem 'dry-struct', '1.6.0'
gem 'faraday', '2.7.7'
gem 'geokit', '1.14.0'
gem 'jaro_winkler', '1.5.6'
gem 'ruby-geometry', '0.0.6', require: 'geometry'
gem 'smartystreets_ruby_sdk', '5.14.19'
gem 'zeitwerk', '2.6.8'

group :development, :test do
  gem 'dotenv', '2.8.1'
  gem 'pry-byebug', '3.10.1'
  gem 'rake', '13.0.6'
  gem 'rspec', '3.12.0'
  gem 'rspec-support', '3.12.1'
  gem 'rubocop', '1.37.1'
  gem 'rubocop-rspec', '2.14.2'
end
